# Generated by Django 6.0.2 on 2026-02-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChromosomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chromosome_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EducationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('sections', models.JSONField()),
                ('tags', models.JSONField(default=list)),
                ('image_svg', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_fact', models.TextField()),
            ],
        ),
    ]
