# Generated by Django 6.0.2 on 2026-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fun_fact', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FunFacts',
        ),
    ]
